app = "notiscope"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"
  target = "production"

[env]
  PORT = "8080"
  # We will set SENDGRID_API_KEY and others via fly secrets

[processes]
  web = "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 1"
  worker = "celery -A app.workers.celery_app worker --loglevel=info --concurrency=1 --queues=notifications,dlq"
  beat = "celery -A app.workers.celery_app beat --loglevel=info --schedule=/tmp/celerybeat-schedule"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
